/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertComponent: typeof import('./src/components/AlertComponent.vue')['default']
    CardComponent: typeof import('./src/components/CardComponent.vue')['default']
    HeaderLayout: typeof import('./src/layouts/HeaderLayout.vue')['default']
    NavbarLayout: typeof import('./src/layouts/NavbarLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableComponent: typeof import('./src/components/TableComponent.vue')['default']
  }
}
